# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('state', models.CharField(choices=[('Unknown', 'Unknown'), ('Done', 'Done'), ('TopPriority', 'TopPriority'), ('BackLog', 'BackLog'), ('Archive', 'Archive')], default='Unknown', max_length=200)),
            ],
        ),
    ]
